# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mini_about.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore


class Ui_mini_about(object):
    def setupUi(self, mini_about):
        mini_about.setObjectName("mini_about")
        mini_about.resize(294, 106)

        self.retranslateUi(mini_about)
        QtCore.QMetaObject.connectSlotsByName(mini_about)

    def retranslateUi(self, mini_about):
        _translate = QtCore.QCoreApplication.translate
        mini_about.setWindowTitle(_translate("mini_about", "Form"))
