# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'unzip.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_unzip_file_dialog(object):
    def setupUi(self, unzip_file_dialog):
        unzip_file_dialog.setObjectName("unzip_file_dialog")
        unzip_file_dialog.resize(521, 60)
        self.label = QtWidgets.QLabel(unzip_file_dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 111, 16))
        self.label.setObjectName("label")
        self.act_label = QtWidgets.QLabel(unzip_file_dialog)
        self.act_label.setGeometry(QtCore.QRect(110, 10, 111, 16))
        self.act_label.setObjectName("act_label")
        self.widget = QtWidgets.QWidget(unzip_file_dialog)
        self.widget.setGeometry(QtCore.QRect(10, 30, 491, 25))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.progressBar = QtWidgets.QProgressBar(self.widget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 0, 0, 1, 1)
        self.exit_button = QtWidgets.QPushButton(self.widget)
        self.exit_button.setObjectName("exit_button")
        self.gridLayout.addWidget(self.exit_button, 0, 1, 1, 1)

        self.retranslateUi(unzip_file_dialog)
        QtCore.QMetaObject.connectSlotsByName(unzip_file_dialog)

    def retranslateUi(self, unzip_file_dialog):
        _translate = QtCore.QCoreApplication.translate
        unzip_file_dialog.setWindowTitle(_translate("unzip_file_dialog", "DGModule运行前准备工作 资源文件释放"))
        self.label.setText(_translate("unzip_file_dialog", "正在解压缩文件"))
        self.act_label.setText(_translate("unzip_file_dialog", "None"))
        self.exit_button.setText(_translate("unzip_file_dialog", "终止解压"))
