# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_welcome(object):
    def setupUi(self, welcome):
        welcome.setObjectName("welcome")
        welcome.resize(402, 191)
        welcome.setMinimumSize(QtCore.QSize(402, 191))
        welcome.setMaximumSize(QtCore.QSize(402, 191))
        self.button_next = QtWidgets.QPushButton(welcome)
        self.button_next.setGeometry(QtCore.QRect(310, 160, 81, 23))
        self.button_next.setObjectName("button_next")
        self.button_about = QtWidgets.QPushButton(welcome)
        self.button_about.setGeometry(QtCore.QRect(10, 160, 75, 23))
        self.button_about.setObjectName("button_about")
        self.groupBox = QtWidgets.QGroupBox(welcome)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 381, 141))
        self.groupBox.setObjectName("groupBox")
        self.text_input_path = QtWidgets.QLineEdit(self.groupBox)
        self.text_input_path.setEnabled(False)
        self.text_input_path.setGeometry(QtCore.QRect(10, 110, 271, 21))
        self.text_input_path.setDragEnabled(False)
        self.text_input_path.setReadOnly(True)
        self.text_input_path.setObjectName("text_input_path")
        self.button_choose_folder = QtWidgets.QPushButton(self.groupBox)
        self.button_choose_folder.setGeometry(QtCore.QRect(290, 110, 75, 21))
        self.button_choose_folder.setObjectName("button_choose_folder")
        self.tab_mode = QtWidgets.QTabWidget(self.groupBox)
        self.tab_mode.setGeometry(QtCore.QRect(10, 20, 361, 81))
        self.tab_mode.setObjectName("tab_mode")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.textEdit = QtWidgets.QTextEdit(self.tab_1)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 361, 61))
        self.textEdit.setObjectName("textEdit")
        self.tab_mode.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_2.setGeometry(QtCore.QRect(0, 0, 361, 61))
        self.textEdit_2.setObjectName("textEdit_2")
        self.tab_mode.addTab(self.tab_2, "")

        self.retranslateUi(welcome)
        self.tab_mode.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(welcome)

    def retranslateUi(self, welcome):
        _translate = QtCore.QCoreApplication.translate
        welcome.setWindowTitle(_translate("welcome", "首次见面 - 配置QPT启动器"))
        self.button_next.setText(_translate("welcome", "下一步"))
        self.button_about.setText(_translate("welcome", "About QPT"))
        self.groupBox.setTitle(_translate("welcome", "QPT环境信息"))
        self.text_input_path.setText(_translate("welcome", "C:/QPT_HOME"))
        self.button_choose_folder.setText(_translate("welcome", "选择文件夹"))
        self.textEdit.setHtml(_translate("welcome", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">由于启动该程序需要QPT环境的支持，故需要选择一个纯英文路径位置存放QPT。</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">若您不了解QPT，请直接点击<span style=\" color:#ff0000;\">下一步</span>即可。</p></body></html>"))
        self.tab_mode.setTabText(self.tab_mode.indexOf(self.tab_1), _translate("welcome", "自动选择"))
        self.textEdit_2.setHtml(_translate("welcome", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">若您已经具备QPT环境，请点击下方“<span style=\" color:#ff0000;\">选择文件夹</span>”来确定<span style=\" color:#ff0000;\">QPT.exe</span>的位置。</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">当然，推荐您使用纯英文路径，这样可以更好兼容C++底层框架。</p></body></html>"))
        self.tab_mode.setTabText(self.tab_mode.indexOf(self.tab_2), _translate("welcome", "手动选择"))
